# Generated by Django 2.0.5 on 2018-06-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('adderss', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_tel', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('station', models.CharField(max_length=255)),
                ('next_station', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('varity', models.CharField(blank=True, max_length=255, null=True)),
                ('send_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_tel', models.CharField(max_length=255)),
                ('station', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
